### ISSUE TITLE
Segfault on Mac when an example ends

### ISSUE THREAD

**Issue by Dentosal** [Blizzard/s2client-api#55] opened 2017-08-10 18:02 UTC
```
me@seeks:build$ ./bin/all_tests 
Running test: sc2::TestAbilityRemap
Launched SC2 (/Applications/StarCraft II/Versions/Base55958/SC2.app/Contents/MacOS/SC2), PID: 75685
NSWindowEdgeResizing is off!
Waiting for connection............
Connected to 127.0.0.1:8167
Waiting for the JoinGame response.
WaitJoinGame finished successfully.
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```

The error is same for at least `./bin/annoying_helper` too. The example itself runs fine, and this error is only thrown after the game window closes.

Running on OS X El Capitan 10.11.6. 

Compiled using:

```bash
git clone --recursive https://github.com/Blizzard/s2client-api
cd s2client-api/
make
mkdir build
cd build/
cmake ../
make
```

(also, compiler weirdness:)

```
[ 96%] Building CXX object tests/CMakeFiles/all_tests.dir/test_observation_interface.cc.o
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:99:90: warning: adding 'int32_t' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
            ReportError("Supply cap is Incorrect the supply is reporting 16 instead of " + obs->GetFoodCap());
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:99:90: note: use array indexing to silence this warning
            ReportError("Supply cap is Incorrect the supply is reporting 16 instead of " + obs->GetFoodCap());
                                                                                         ^
                        &                                                                [                  ]
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:249:117: warning: adding 'uint32_t' (aka 'unsigned int') to a string does not append to the string
      [-Wstring-plus-int]
                std::string errorStr = "UnitTypeData is reporting an incorrect cargo value. Expected : 0 Result : " + stalker_data.cargo_size;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:249:117: note: use array indexing to silence this warning
                std::string errorStr = "UnitTypeData is reporting an incorrect cargo value. Expected : 0 Result : " + stalker_data.cargo_size;
                                                                                                                    ^
                                       &                                                                            [                        ]
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:253:126: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                std::string errorStr = "UnitTypeData is reporting an incorrect mineral cost value. Expected : 125 Result : " + stalker_data.mineral_cost;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:253:126: note: use array indexing to silence this warning
                std::string errorStr = "UnitTypeData is reporting an incorrect mineral cost value. Expected : 125 Result : " + stalker_data.mineral_cost;
                                                                                                                             ^
                                       &                                                                                     [                          ]
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:257:120: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                std::string errorStr = "UnitTypeData is reporting an incorrect vespene value. Expected : 50 Result : " + stalker_data.vespene_cost;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:257:120: note: use array indexing to silence this warning
                std::string errorStr = "UnitTypeData is reporting an incorrect vespene value. Expected : 50 Result : " + stalker_data.vespene_cost;
                                                                                                                       ^
                                       &                                                                               [                          ]
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:265:116: warning: adding 'uint32_t' (aka 'unsigned int') to a string does not append to the string
      [-Wstring-plus-int]
                std::string errorStr = "UnitTypeData is reporting an incorrect unittypeID Expected : 74 Result : " + stalker_data.unit_type_id;
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Hannes/Desktop/s2client-api/tests/test_observation_interface.cc:265:116: note: use array indexing to silence this warning
                std::string errorStr = "UnitTypeData is reporting an incorrect unittypeID Expected : 74 Result : " + stalker_data.unit_type_id;
                                                                                                                   ^
                                       &                                                                           [                          ]
5 warnings generated.
```

**Comment by KevinCalderone** [comment] 2017-08-10 18:05
I think I know what the issue is. Will investigate.

**Comment by KevinCalderone** [comment] 2017-08-10 23:51
Those warnings should be fixed now too.

**Closed by KevinCalderone** 2017-08-10 23:51 UTC
