### ISSUE TITLE
Please add support for high DPI monitor

### ISSUE THREAD

**Issue by cpus133525** [Blizzard/s2client-api#126] opened 2017-09-08 05:29 UTC
When I use some laptops with high DPI monitor, the texts the bot print are rather small and I can't see it clearly since the Starcraft II process is per-moniter aware. Could you please add support for high DPI monitor? Thanks!

**Comment by KevinCalderone** [comment] 2017-09-11 22:45
This is a duplicate of #31.

Thanks for the feedback. I agree it would be nice to have a size option.

**Closed by KevinCalderone** 2017-09-11 22:45 UTC
